#pragma config(Sensor, in1,    frontsonar,     sensorSONAR, int1)
#pragma config(Sensor, in2,    rightsonar,     sensorSONAR, int2)
#pragma config(Motor,  port1,           leftfrontmotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           rightfrontmotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftbackmotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           rightbackmotor, tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 // int speed;
 // int speed2; // Will hold a speed for the motors.
 // int distance = 20;    // Specified distance to be at 25 centimeters.
  int flag = 0;
  int counter = 0;

  while(flag == 0)
  {
    if(SensorValue(frontsonar) > 10 || SensorValue(frontsonar) == -1)  // If the object is out of range: (returns -1)
  {
  {
    	motor[leftfrontmotor]  = 82;
      motor[rightfrontmotor] = 60;
      motor[leftbackmotor]  = 82;
      motor[rightbackmotor] = 60;// Set 'speed' to full speed ahead!
      wait1Msec(100);

      if(SensorValue(rightsonar) < 25)
      {
    	motor[leftfrontmotor]  = 82;
      motor[rightfrontmotor] = 60;
      motor[leftbackmotor]  = 82;
      motor[rightbackmotor] = 60;// Set 'speed' to full speed ahead!
      wait1Msec(98);
    	}
      else
      counter = counter + 1;
 			}
      if (counter > 4)
      {
    	motor[leftfrontmotor]  = 0;
      motor[rightfrontmotor] = 0;
      motor[leftbackmotor]  = 0;
      motor[rightbackmotor] = 0;// Set 'speed' to zero
      wait1Msec(100);
    	motor[leftfrontmotor]  = -40;
      motor[rightfrontmotor] = 20;
      motor[leftbackmotor]  = -40;
      motor[rightbackmotor] = 20;
      wait1Msec(800);
      motor[leftfrontmotor]  = -40;
      motor[rightfrontmotor] = -40;
      motor[leftbackmotor]  = -40;
      motor[rightbackmotor] = -40;
      wait1Msec(525);
      motor[leftfrontmotor]  = 20;
      motor[rightfrontmotor] = -40;
      motor[leftbackmotor]  = 20;
      motor[rightbackmotor] = -40;// Set 'speed' to zero
      wait1Msec(610);
      flag = 1;
    }
  }
    else
    {
    	motor[leftfrontmotor]  = 0;
      motor[rightfrontmotor] = 0;
      motor[leftbackmotor]  = 0;
      motor[rightbackmotor] = 0;
      wait1Msec(5000);
    	}
    }
  }
